package com.samsonych.jwp.model;

// Generated 21.12.2010 7:24:07 by Hibernate Tools 3.4.0.Beta1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WpComments generated by hbm2java
 */
@Entity
@Table(name = "comments")
public class Comment implements java.io.Serializable {

    private static final long serialVersionUID = 1203047723223880727L;
    private Long commentId;
    private Post post;
    private String commentAuthor;
    private String commentAuthorEmail;
    private String commentAuthorUrl;
    private String commentAuthorIp;
    private Date commentDate;
    private Date commentDateGmt;
    private String commentContent;
    private int commentKarma;
    private String commentApproved;
    private String commentAgent;
    private String commentType;
    private long commentParent;
    private long userId;

    public Comment() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "comment_ID", unique = true, nullable = false)
    public Long getCommentId() {
        return this.commentId;
    }

    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    @ManyToOne(cascade = CascadeType.REFRESH, fetch = FetchType.LAZY)
    @JoinColumn(name = "comment_post_ID", nullable = false)
    public Post getPost() {
        return this.post;
    }

    public void setPost(Post post) {
        this.post = post;
    }

    @Column(name = "comment_author", nullable = false)
    public String getCommentAuthor() {
        return this.commentAuthor;
    }

    public void setCommentAuthor(String commentAuthor) {
        this.commentAuthor = commentAuthor;
    }

    @Column(name = "comment_author_email", nullable = false, length = 100)
    public String getCommentAuthorEmail() {
        return this.commentAuthorEmail;
    }

    public void setCommentAuthorEmail(String commentAuthorEmail) {
        this.commentAuthorEmail = commentAuthorEmail;
    }

    @Column(name = "comment_author_url", nullable = false, length = 200)
    public String getCommentAuthorUrl() {
        return this.commentAuthorUrl;
    }

    public void setCommentAuthorUrl(String commentAuthorUrl) {
        this.commentAuthorUrl = commentAuthorUrl;
    }

    @Column(name = "comment_author_IP", nullable = false, length = 100)
    public String getCommentAuthorIp() {
        return this.commentAuthorIp;
    }

    public void setCommentAuthorIp(String commentAuthorIp) {
        this.commentAuthorIp = commentAuthorIp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "comment_date", nullable = false, length = 19)
    public Date getCommentDate() {
        return this.commentDate;
    }

    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "comment_date_gmt", nullable = false, length = 19)
    public Date getCommentDateGmt() {
        return this.commentDateGmt;
    }

    public void setCommentDateGmt(Date commentDateGmt) {
        this.commentDateGmt = commentDateGmt;
    }

    @Column(name = "comment_content", nullable = false, length = 65535)
    public String getCommentContent() {
        return this.commentContent;
    }

    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent;
    }

    @Column(name = "comment_karma", nullable = false)
    public int getCommentKarma() {
        return this.commentKarma;
    }

    public void setCommentKarma(int commentKarma) {
        this.commentKarma = commentKarma;
    }

    @Column(name = "comment_approved", nullable = false, length = 20)
    public String getCommentApproved() {
        return this.commentApproved;
    }

    public void setCommentApproved(String commentApproved) {
        this.commentApproved = commentApproved;
    }

    @Column(name = "comment_agent", nullable = false)
    public String getCommentAgent() {
        return this.commentAgent;
    }

    public void setCommentAgent(String commentAgent) {
        this.commentAgent = commentAgent;
    }

    @Column(name = "comment_type", nullable = false, length = 20)
    public String getCommentType() {
        return this.commentType;
    }

    public void setCommentType(String commentType) {
        this.commentType = commentType;
    }

    @Column(name = "comment_parent", nullable = false)
    public long getCommentParent() {
        return this.commentParent;
    }

    public void setCommentParent(long commentParent) {
        this.commentParent = commentParent;
    }

    @Column(name = "user_id", nullable = false)
    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

}
