package com.samsonych.model.wp;

// Generated 21.12.2010 7:24:07 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WpCommentmeta generated by hbm2java
 */
@Entity
@Table(name = "commentmeta")
public class CommentMeta implements java.io.Serializable {

    private static final long serialVersionUID = -4981598592875279497L;
    private Long metaId;
    private Comment comment;
    private String metaKey;
    private String metaValue;

    public CommentMeta() {
    }

    public CommentMeta(Comment comment) {
        this.comment = comment;
    }

    public CommentMeta(Comment comment, String metaKey, String metaValue) {
        this.comment = comment;
        this.metaKey = metaKey;
        this.metaValue = metaValue;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "meta_id", unique = true, nullable = false)
    public Long getMetaId() {
        return this.metaId;
    }

    public void setMetaId(Long metaId) {
        this.metaId = metaId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    public Comment getComment() {
        return this.comment;
    }

    public void setComment(Comment comment) {
        this.comment = comment;
    }

    @Column(name = "meta_key")
    public String getMetaKey() {
        return this.metaKey;
    }

    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey;
    }

    @Column(name = "meta_value")
    public String getMetaValue() {
        return this.metaValue;
    }

    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue;
    }

}
