package com.samsonych.model.wp;

// Generated 21.12.2010 7:24:07 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WpCommentmeta generated by hbm2java
 */
@Entity
@Table(name = "wp_commentmeta", catalog = "gads_wp")
public class WpCommentmeta implements java.io.Serializable {

    private Long metaId;
    private long commentId;
    private String metaKey;
    private String metaValue;

    public WpCommentmeta() {
    }

    public WpCommentmeta(long commentId) {
        this.commentId = commentId;
    }

    public WpCommentmeta(long commentId, String metaKey, String metaValue) {
        this.commentId = commentId;
        this.metaKey = metaKey;
        this.metaValue = metaValue;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "meta_id", unique = true, nullable = false)
    public Long getMetaId() {
        return this.metaId;
    }

    public void setMetaId(Long metaId) {
        this.metaId = metaId;
    }

    @Column(name = "comment_id", nullable = false)
    public long getCommentId() {
        return this.commentId;
    }

    public void setCommentId(long commentId) {
        this.commentId = commentId;
    }

    @Column(name = "meta_key")
    public String getMetaKey() {
        return this.metaKey;
    }

    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey;
    }

    @Column(name = "meta_value")
    public String getMetaValue() {
        return this.metaValue;
    }

    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue;
    }

}
