package com.samsonych.model.wp;

// Generated 21.12.2010 7:24:07 by Hibernate Tools 3.4.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WpUsermeta generated by hbm2java
 */
@Entity
@Table(name = "wp_usermeta", catalog = "gads_wp")
public class WpUsermeta implements java.io.Serializable {

    private Long umetaId;
    private long userId;
    private String metaKey;
    private String metaValue;

    public WpUsermeta() {
    }

    public WpUsermeta(long userId) {
        this.userId = userId;
    }

    public WpUsermeta(long userId, String metaKey, String metaValue) {
        this.userId = userId;
        this.metaKey = metaKey;
        this.metaValue = metaValue;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "umeta_id", unique = true, nullable = false)
    public Long getUmetaId() {
        return this.umetaId;
    }

    public void setUmetaId(Long umetaId) {
        this.umetaId = umetaId;
    }

    @Column(name = "user_id", nullable = false)
    public long getUserId() {
        return this.userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    @Column(name = "meta_key")
    public String getMetaKey() {
        return this.metaKey;
    }

    public void setMetaKey(String metaKey) {
        this.metaKey = metaKey;
    }

    @Column(name = "meta_value")
    public String getMetaValue() {
        return this.metaValue;
    }

    public void setMetaValue(String metaValue) {
        this.metaValue = metaValue;
    }

}
